// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enampjykqzykwdrxyefa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuYW1wanlrcXp5a3dkcnh5ZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjQ3MzcsImV4cCI6MjA1NTU0MDczN30.KkG1aTKFdvsBOUGxg3cNTJeQ1K1JjBiUz6JCy4nocZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);